services:
  builder:
    image: tardis-io/rp2040-kbd-converter
    build:
      context: .
      dockerfile: Dockerfile
    user: "1001:1001"
    restart: never
    environment:
      - KEYBOARD
      - MOUSE
    volumes:
      - ./src:/usr/local/builder/src
      - ./build:/usr/local/builder/build:rw
