#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
#
# filter_compile_db.py — Filter a CMake compile_commands.json to project files only.
#
# Removes SDK and generated-file entries so that static-analysis tools only see
# the project's own source files.
#
# Usage:
#   python3 filter_compile_db.py <input_db> <output_db> <src_prefix>
#
# Arguments:
#   input_db    — path to the full compile_commands.json generated by cmake
#   output_db   — path to write the filtered compile_commands.json
#   src_prefix  — only entries whose 'file' starts with this prefix are kept
#                 (e.g. /usr/local/builder/src/)
#
# Exits non-zero if the output database contains no entries.

import json
import sys


def main() -> None:
    if len(sys.argv) != 4:
        print(
            "Usage: filter_compile_db.py <input_db> <output_db> <src_prefix>",
            file=sys.stderr,
        )
        sys.exit(1)

    input_db, output_db, src_prefix = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(input_db) as f:
        db = json.load(f)

    filtered = [e for e in db if e["file"].startswith(src_prefix)]

    print(f"  filtered: {len(db)} total entries -> {len(filtered)} project entries")

    if not filtered:
        print(
            f"ERROR: no entries matched prefix '{src_prefix}'",
            file=sys.stderr,
        )
        sys.exit(1)

    with open(output_db, "w") as f:
        json.dump(filtered, f, indent=2)


if __name__ == "__main__":
    main()
