name: Test Building of Converter Firmwares

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Build Container
      run: docker compose build
    - name: Run Build for Model F 6450225
      run: docker compose run -e KEYBOARD="modelf/6450225" builder
    - name: Run Build for Model M 1390131
      run: docker compose run -e KEYBOARD="modelm/1390131" builder
    - name: Run Build for Cherry G80-0614H
      run: docker compose run -e KEYBOARD="cherry/G80-0614H" builder
    - name: Run Build for Cherry G80-1104H
      run: docker compose run -e KEYBOARD="cherry/G80-1104H" builder
    - name: Run Build for MicroSwitch 122ST13
      run: docker compose run -e KEYBOARD="microswitch/122st13" builder
